### ISSUE TITLE
Regular tilp configure allows exit of home directory (despite not passing the argument)

### ISSUE THREAD

**Issue by parkerlreed** [debrouxl/tilp_and_gfm#11]
Compiled everything with stock `autoreconf -i -f; ./configure --prefix=/usr`

I noticed the message about --enable-exit-homedir in the README but didn't pass it. When I run tilp I am able to traverse up to / and into other folders.

**Comment by adriweb** [comment]
Regarding your compile sentence, in case something didn't go as planned, I created a step-by-step tutorial for mac building here, based on the install script: https://tiplanet.org/forum/viewtopic.php?f=2&t=17297.
That said, it doesn't look like you had an issue building it, so that's good.
However, "I am able to traverse up to / and into other folders" does not sound like an actual bug/issue. The configure parameter is used to specify where to install upon `make install`.

**Comment by parkerlreed** [comment]
I'm specific​ally talking about `--enable-exit-homedir`. The READMe made it sound like this should be off by default and have to be explicitly enabled. I did NOT specify this and yet i was able to browse my full filesystem.

**Comment by adriweb** [comment]
Well, the changelog indicates this was added back in 2001 and enabled by default in 2004.

**Comment by parkerlreed** [comment]
Ahh thanks! The wording here is a little ambiguous https://github.com/debrouxl/tilp_and_gfm/blob/master/tilp/trunk/README.linux#L42
