### ISSUE TITLE
Download Functionality for command line

### ISSUE THREAD

**Issue by M47H3W** [debrouxl/tilp_and_gfm#32]
Through the command line, TILP2 can upload programs to calculators, but would it be possible to download programs too as well other stuff like single named-variables or strings (Str1, Str2, Str3, etc.)?

**Comment by debrouxl** [comment]
It would indeed be possible. However, such functionality is better implemented by simple, lightweight CLI tools which do not have a runtime dependency on GUI libraries, icons, etc.
There are two such thin wrappers over the file-related and linking-related functionality of the libti* stack:
* TITools: https://www.ticalc.org/archives/files/fileinfo/430/43083.html / https://github.com/Jonimoose/TITools ;
* libticalcs' test_ticalcs_2, which can get files to a certain extent, and is scriptable.

TITools was there first, and while I greatly expanded the functionality of test_ticalcs_2 over time, especially after the TILP II 1.18 release train, I'd probably use TITools for the use case you describe: test_ticalcs_2 is more of a reference implementation and developer power tool :)

I hope that this helps.

**Comment by M47H3W** [comment]
I tried using TITools, but unfortunately all of the programs won't work for some reason, either giving me a transmission error or packet error. I tried it on three different calculator models. Screenshot: https://i.imgur.com/sagglS4.png

What would be the easiest way to get and compile test_ticalcs_2 ?

**Comment by debrouxl** [comment]
When a single calculator of your choice is plugged in to your computer, is it automatically detected, and can you successfully communicate with it ? If not, you need to fix that first; on Windows, the main source of communication issues is Windows' driver limitations, but on Linux, it's a lack of udev rules, because they haven't been installed by a distro packages or by the user.

To answer your question: test_ticalcs_2 is produced as part of building libticalcs, e.g. with the standard build script https://github.com/debrouxl/tilp_and_gfm/raw/master/tilp/trunk/build/scripts/install_tilp.sh , which lists build dependencies for a range of distros, and reminds the user to read the CONFIG file containing information on installing the udev rules.
The best version of test_ticalcs_2 is in the experimental2 branch, but the script does not support building straight from the experimental2 branch without minor modifications. It makes me think that I should replace that "USE_EXPERIMENTAL" environment variable by two variables triggering the usage of the given branch, defaulting to master, for tilibs and tilp_and_gfm...

**Comment by M47H3W** [comment]
I had been able to communicate with the calculators via the TILP GUI and the non-GUI interface, but TITools wouldn't work even though TILP did. Reinstalling all of the libraries seems to have got it to work for me and I no longer have those invalid packet errors.


One issue I kept running into was that I could not get something to build because it required libtifiles >= 1.1.5 while I only had 1.1.4. I'm not sure why the latest isn't automatically installed, but I had to resolve it through manually looking for the package .deb files online to install them.
