### ISSUE TITLE
trying to transfer MirageOs produces an issue stating "Invalid Parameter" 

### ISSUE THREAD

**Issue by Laar3** [debrouxl/tilp_and_gfm#50]
when trying to transfer the file (which is a .8xk) i recieve the following error 
![image](https://user-images.githubusercontent.com/77225642/144023284-5cf14daf-39cd-4043-ad2e-09487ed8fa83.png)

link to the software im trying to install is here https://detachedsolutions.com/mirageos/manual/install.php#setup
the calculator is a ti-84 plus CE and it is running version 5.4 of its os.

the host computer is running arch linux.

**Comment by adriweb** [comment]
MirageOS is an app for the (original) TI-83 Plus and TI-84 Plus, not the CE series.
You can download [Cesium](https://github.com/mateoconlechuga/cesium/releases/latest) instead, for the CE.

**Comment by Laar3** [comment]
Oh I wasn't aware. Thanks

**Comment by debrouxl** [comment]
You did it right to create this issue, this is the modern approach for what the error message requests :)

The error message does not point to the root cause of the issue you're seeing, described by Adriweb, but at least, the error prevents, relatively early on, the transfer from occurring. If it proceeded, the calculator would reject the FlashApp later anyway.
